Repository jupyter-server/jupyter_server, pull requests merged in 2021-09, with the labels that each got.

#580 pytest_plugin: allow user specified headers in jp_ws_fetch
  jupyter_server/pytest_plugin.py
Labels: bug

#579 Shutdown kernels/terminals on api/shutdown
  jupyter_server/base/handlers.py
  jupyter_server/services/shutdown.py
Labels: bug

#581 Fix jupyter_client warning
  jupyter_server/base/zmqhandlers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/sessions/handlers.py
Labels: maintenance

#582 Automated Changelog Entry for 1.11.0 on master
  CHANGELOG.md
Labels: documentation

#584 Do not log connection error if the kernel is already shutdown
  jupyter_server/services/kernels/handlers.py
Labels: bug
