Repository jupyter-server/jupyter_server, pull requests merged in 2021-07, with the labels that each got.

#548 Rebuild package-lock, fixing local setup
  package-lock.json
Labels: bug

#523 extensions: allow extensions in namespace packages
  jupyter_server/extension/application.py
  jupyter_server/tests/namespace-package-test/README.md
  jupyter_server/tests/namespace-package-test/setup.cfg
  jupyter_server/tests/namespace-package-test/test_namespace/test_package/__init__.py
  jupyter_server/tests/test_utils.py
  jupyter_server/utils.py
Labels: enhancement

#526 stop hook for extensions
  docs/source/developers/extensions.rst
  jupyter_server/extension/application.py
  jupyter_server/extension/manager.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/tests/extension/test_app.py
  jupyter_server/utils.py
Labels: enhancement

#541 small test changes
  .github/workflows/downstream.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  CONTRIBUTING.rst
  README.md
  conftest.py
  examples/simple/tests/conftest.py
  jupyter_server/auth/security.py
  jupyter_server/traittypes.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#556 Protect against unset spec
  jupyter_server/tests/test_utils.py
  jupyter_server/utils.py
Labels: bug

#557 Automated Changelog Entry for 1.10.1 on master
  CHANGELOG.md
Labels: documentation
