Repository jupyter-server/jupyter_server, pull requests merged in 2021-11, with the labels that each got.

#607 Consistent logging method
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/handlers.py
Labels: enhancement

#613 Enforce labels on PRs
  .github/workflows/enforce-label.yml
Labels: maintenance

#608 test_api: Normalize file name and path
  jupyter_server/tests/services/contents/test_api.py
Labels: maintenance

#593 Use pending kernels
  jupyter_server/base/zmqhandlers.py
  jupyter_server/pytest_plugin.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/tests/services/kernels/test_api.py
  jupyter_server/tests/services/kernels/test_cull.py
  jupyter_server/tests/services/kernelspecs/test_api.py
  jupyter_server/tests/services/sessions/test_api.py
Labels: enhancement

#615 Automated Changelog Entry for 1.12.0 on master
  CHANGELOG.md
Labels: documentation

#616 Use maintainer-tools base setup action
  .github/workflows/check-release.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
Labels: maintenance

#617 await _finish_kernel_start
  jupyter_server/services/kernels/kernelmanager.py
Labels: bug

#618 Update to Python 3.10 in the CI workflows
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
Labels: maintenance

#619 Automated Changelog Entry for 1.12.1 on master
  CHANGELOG.md
Labels: documentation

#620 Clean up version info handling
  jupyter_server/_version.py
  pyproject.toml
Labels: maintenance
