Repository jupyter-server/jupyter_server, pull requests merged in 2021-03, with the labels that each got.

#450 Implement password hashing with argon2-cffi
  jupyter_server/auth/security.py
  jupyter_server/tests/auth/test_security.py
  setup.py
Labels: backwards compat

#452 Add Styling to the HTML Pages
  .gitignore
  CONTRIBUTING.rst
  jupyter_server/static/style/index.css
  jupyter_server/templates/browser-open.html
  jupyter_server/templates/error.html
  jupyter_server/templates/login.html
  jupyter_server/templates/logout.html
  jupyter_server/templates/main.html
  jupyter_server/templates/page.html
  jupyter_server/templates/view.html
  package-lock.json
  package.json
  setup.py
Labels: backwards compat

#454 Ensure jupyter config dir exist
  jupyter_server/auth/security.py
Labels: backwards compat, bug

#461 Add env variable support for port options
  jupyter_server/serverapp.py
Labels: backwards compat, feature

#463 Update description for kernel restarted in the API docs
  jupyter_server/services/api/api.yaml
Labels: documentation

#464 Remove unnecessary future imports
  jupyter_server/__main__.py
  jupyter_server/_sysinfo.py
  jupyter_server/utils.py
Labels: backwards compat, maintenance
