Repository jupyter-server/jupyter_server, pull requests merged in 2021-04, with the labels that each got.

#472 Fix race condition with async kernel management
  jupyter_server/services/kernels/kernelmanager.py
Labels: backwards compat, bug

#476 Update Changelog for 1.6.1
  CHANGELOG.md
Labels: documentation

#477 Use Jupyter Packaging
  .github/workflows/codeql-analysis.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  CHANGELOG.md
  CONTRIBUTING.rst
  MANIFEST.in
  README.md
  RELEASE.md
  jupyter_server/_version.py
  package-lock.json
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  setupbase.py
Labels: maintenance

#478 Tighten xsrf checks
  jupyter_server/base/handlers.py
  jupyter_server/files/handlers.py
  jupyter_server/nbconvert/handlers.py
Labels: backwards compat, enhancement

#479 Re-enable support for answer_yes flag
  jupyter_server/serverapp.py
Labels: backwards compat, bug

#480 Add changelog for 1.6.2
  CHANGELOG.md
Labels: documentation

#484 Update changelog for 1.6.3
  CHANGELOG.md
Labels: documentation

#485 Fix loading of sibling extensions
  jupyter_server/extension/application.py
  jupyter_server/tests/extension/mockextensions/app.py
  jupyter_server/tests/extension/test_app.py
Labels: bug

#440 Remove some of ipython_genutils no-op.
  jupyter_server/base/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/config/handlers.py
  jupyter_server/services/contents/filecheckpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/tests/nbconvert/test_handlers.py
  jupyter_server/tests/test_gateway.py
  jupyter_server/utils.py
Labels: maintenance

#493 DOC: Autoreformat docstrings.
  jupyter_server/_sysinfo.py
  jupyter_server/_tz.py
  jupyter_server/auth/login.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/extension/serverextension.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/checkpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/tests/services/sessions/test_api.py
  jupyter_server/utils.py
Labels: documentation

#494 Prep for Release Helper Usage
  .github/workflows/check-release.yml
  .github/workflows/python-linux.yml
  CHANGELOG.md
  MANIFEST.in
  RELEASE.md
Labels: maintenance

#497 Fix for recursive symlink - (port Notebook 4670)
  jupyter_server/services/contents/filemanager.py
  jupyter_server/tests/services/contents/test_manager.py
Labels: bug
