Repository jupyter-server/jupyter_server, pull requests merged in 2021-12, with the labels that each got.

#628 Nudge on the control channel instead of the shell
  jupyter_server/services/kernels/handlers.py
Labels: bug

#629 Clean up downstream tests
  .github/workflows/downstream.yml
Labels: maintenance

#614 Persistent session storage
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/tests/services/sessions/test_manager.py
Labels: enhancement

#631 Automated Changelog Entry for 1.13.0 on master
  CHANGELOG.md
Labels: documentation

#632 Fix macos pypy check
  .github/workflows/python-macos.yml
Labels: maintenance

#636 nudge both the shell and control channels
  jupyter_server/services/kernels/handlers.py
Labels: bug

#637 Automated Changelog Entry for 0.13.1 on master
  CHANGELOG.md
Labels: documentation

#635 remove redundant pylint check
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/simple/conftest.py
  jupyter_server/__init__.py
  jupyter_server/auth/__init__.py
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
  jupyter_server/services/config/__init__.py
  jupyter_server/utils.py
  setup.cfg
Labels: maintenance

#641 handle KeyError when get session
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/tests/services/sessions/test_manager.py
  package-lock.json
Labels: bug

#643 Run pre_save_hook before model check
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
Labels: bug

#634 pyproject.toml: clarify build system version
  pyproject.toml
Labels: maintenance

#646 Update branch references
  .github/workflows/check-release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  CONTRIBUTING.rst
  README.md
  docs/source/developers/extensions.rst
  docs/source/index.rst
  jupyter_server/serverapp.py
Labels: maintenance

#650 Clean up deprecations
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  docs/environment.yml
  docs/source/conf.py
  examples/simple/setup.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  setup.cfg
Labels: maintenance
