Repository jupyter-server/jupyter_server, pull requests merged in 2021-05, with the labels that each got.

#498 Automated Changelog Entry for 1.7.0a0 on master
  CHANGELOG.md
Labels: documentation

#503 ExtensionPoint: return True on successful validate()
  jupyter_server/extension/manager.py
  jupyter_server/extension/serverextension.py
  jupyter_server/tests/extension/test_manager.py
Labels: maintenance

#502 ExtensionManager: load default config manager by default
  jupyter_server/extension/manager.py
  jupyter_server/tests/extension/test_manager.py
Labels: maintenance

#483 Refactor gateway kernel management to achieve a degree of consistency
  docs/source/other/full-config.rst
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/tests/test_gateway.py
  setup.cfg
Labels: enhancement

#506 Include backtrace in debug output when extension fails to load
  jupyter_server/extension/manager.py
Labels: maintenance

#507 Automated Changelog Entry for 1.7.0a1 on master
  CHANGELOG.md
Labels: documentation

#509 Increase minimum jupyter_core dependency
  setup.cfg
Labels: maintenance

#510 Automated Changelog Entry for 1.7.0a2 on master
  CHANGELOG.md
Labels: documentation

#512 Make nbconvert root handler asynchronous
  jupyter_server/services/nbconvert/handlers.py
Labels: enhancement

#511 Use kernel_id for new kernel if it doesn't exist in MappingKernelManager.start_kernel
  jupyter_server/services/kernels/kernelmanager.py
Labels: maintenance

#515 Remove Packaging Dependency
  jupyter_server/_version.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#516 Automated Changelog Entry for 1.7.0 on master
  CHANGELOG.md
Labels: documentation

#517 init_httpserver at the end of initialize
  jupyter_server/serverapp.py
Labels: bug

#513 restore preference for SelectorEventLoop on Windows
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
Labels: maintenance

#504 set default config dir name
  jupyter_server/services/config/manager.py
Labels: maintenance

#519 Enable Server Tests on Windows
  jupyter_server/tests/extension/test_manager.py
  jupyter_server/tests/test_terminal.py
Labels: maintenance

#521 Upgrade anyio to 3.1 for all py versions
  jupyter_server/services/contents/filecheckpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
  jupyter_server/services/nbconvert/handlers.py
  setup.cfg
Labels: maintenance

#522 Expose a public property to sort extensions deterministically.
  jupyter_server/extension/manager.py
Labels: enhancement

#524 Automated Changelog Entry for 1.8.0 on master
  CHANGELOG.md
Labels: documentation

#525 [Notebook port 4835] Add UNIX socket support to notebook server
  .github/workflows/integration-tests.yml
  jupyter_server/__init__.py
  jupyter_server/base/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/tests/conftest.py
  jupyter_server/tests/test_serverapp.py
  jupyter_server/tests/unix_sockets/__init__.py
  jupyter_server/tests/unix_sockets/conftest.py
  jupyter_server/tests/unix_sockets/test_api.py
  jupyter_server/tests/unix_sockets/test_serverapp_integration.py
  jupyter_server/utils.py
  setup.cfg
Labels: backwards compat, enhancement

#527 fix jp_ws_fetch not work by its own #441
  jupyter_server/pytest_plugin.py
Labels: maintenance

#528 Test Downstream Packages
  .github/workflows/downstream.yml
Labels: maintenance
