Repository jupyter-server/jupyter_server, pull requests merged in 2022-03, with the labels that each got.

#704 Add Minimum Requirements Test
  .github/workflows/python-linux.yml
Labels: maintenance

#707 Clean up Dependency Handling
  .github/workflows/python-linux.yml
  setup.cfg
Labels: maintenance

#715 Re-use ServerApp.config_file_paths for consistency
  jupyter_server/extension/application.py
  jupyter_server/serverapp.py
Labels: bug

#716 Call pre_save_hook only on first chunk of large files
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
Labels: bug

#706 Fall back to legacy protocol if selected_subprotocol raises exception
  jupyter_server/services/kernels/handlers.py
Labels: bug

#721 Implement Required Methods in Async Manner
  jupyter_server/services/contents/filemanager.py
Labels: bug

#722 Clean up activity recording
  jupyter_server/services/kernels/kernelmanager.py
Labels: maintenance

#723 Clean up CI
  .github/workflows/downstream.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  package-lock.json
  pyproject.toml
  tests/conftest.py
  tests/services/kernels/test_api.py
  tests/services/sessions/test_api.py
Labels: maintenance

#696 Register pre/post save hooks, call them sequentially
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
  jupyter_server/services/contents/manager.py
  tests/test_files.py
Labels: enhancement

#726 Automated Changelog Entry for 1.15.0 on main
  CHANGELOG.md
Labels: documentation

#728 Revert "Re-use ServerApp.config_file_paths for consistency (#715)"
  jupyter_server/extension/application.py
  jupyter_server/serverapp.py
Labels: bug

#729 Automated Changelog Entry for 1.15.1 on main
  CHANGELOG.md
Labels: documentation

#725 Skip nbclassic downstream tests for now
  .github/workflows/downstream.yml
Labels: maintenance

#718 Avoid usage of ipython_genutils
  jupyter_server/_sysinfo.py
  jupyter_server/auth/security.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/gateway/handlers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/terminal/__init__.py
  jupyter_server/utils.py
  setup.cfg
  tests/services/contents/test_fileio.py
Labels: maintenance

#732 Revert "Server extension paths (#730)"
  jupyter_server/extension/application.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
  tests/extension/test_app.py
Labels: bug

#734 Fix server-extension paths (3rd time's the charm)
  jupyter_server/extension/application.py
  jupyter_server/serverapp.py
  tests/extension/test_app.py
Labels: bug

#735 Automated Changelog Entry for 1.15.3 on main
  CHANGELOG.md
Labels: documentation

#736 Fix sdist test
  .github/workflows/python-linux.yml
  jupyter_server/log.py
  tests/extension/test_launch.py
Labels: maintenance

#738 raise no-authorization warning once and allow disabled authorization
  jupyter_server/auth/decorator.py
Labels: bug

#739 Relax type checking on ExtensionApp.serverapp
  jupyter_server/extension/application.py
Labels: bug

#740 Automated Changelog Entry for 1.15.5 on main
  CHANGELOG.md
Labels: documentation

#741 Clean up downstream tests
  .github/workflows/downstream.yml
Labels: maintenance

#744 Missing warning when no authorizer in found ZMQ handlers
  jupyter_server/auth/decorator.py
  jupyter_server/auth/utils.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/terminal/handlers.py
Labels: bug

#742 More CI Cleanup
  .github/workflows/python-linux.yml
  .mailmap
  .pre-commit-config.yaml
  docs/Makefile
  docs/autogen_config.py
  docs/source/conf.py
  examples/simple/jupyter_server_config.py
  examples/simple/pytest.ini
  examples/simple/simple_ext11/application.py
  jupyter_server/auth/login.py
  jupyter_server/auth/logout.py
  jupyter_server/auth/security.py
  jupyter_server/base/handlers.py
  jupyter_server/extension/application.py
  jupyter_server/extension/manager.py
  jupyter_server/extension/serverextension.py
  jupyter_server/extension/utils.py
  jupyter_server/gateway/managers.py
  jupyter_server/i18n/__init__.py
  jupyter_server/i18n/babel_nbui.cfg
  jupyter_server/nbconvert/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/terminalmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  setup.cfg
  tests/auth/test_authorizer.py
  tests/auth/test_security.py
  tests/extension/mockextensions/app.py
  tests/extension/mockextensions/mock1.py
  tests/extension/mockextensions/mock2.py
  tests/extension/mockextensions/mockext_both.py
  tests/extension/mockextensions/mockext_py.py
  tests/extension/mockextensions/mockext_sys.py
  tests/extension/mockextensions/mockext_user.py
  tests/extension/test_launch.py
  tests/services/contents/test_manager.py
  tests/services/kernels/test_api.py
  tests/services/nbconvert/test_api.py
  tests/services/sessions/test_api.py
  tests/test_gateway.py
  tests/test_terminal.py
  tests/unix_sockets/test_api.py
Labels: maintenance

#745 Automated Changelog Entry for 1.15.6 on main
  CHANGELOG.md
Labels: documentation

#747 Clean up workflows
  .github/workflows/python-macos.yml
  .github/workflows/python-tests.yml
  .github/workflows/python-windows.yml
Labels: maintenance

#748 wait to cleanup kernels after kernel is finished pending
  jupyter_server/services/kernels/kernelmanager.py
Labels: bug

#757 Include explicit package data
  setup.cfg
Labels: bug

#756 Ensure minimal nbconvert support jinja2 v2 & v3
  setup.cfg
Labels: maintenance

#761 Regression in connection URL calcuation in ServerApp
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: bug

#763 Install pre-commit automatically
  CONTRIBUTING.rst
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#764 Update pre-commit
  .pre-commit-config.yaml
Labels: maintenance

#765 Remove redundant job and problematic check
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
Labels: maintenance

#766 Skip jsonschema in CI
  .pre-commit-config.yaml
Labels: maintenance

#760 Add `max-age` Cache-Control header to kernel logos
  jupyter_server/kernelspecs/handlers.py
Labels: enhancement

#720 Remove Redundant Dir_Exists Invocation When Creating New Files with ContentsManager
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  tests/services/contents/test_manager.py
Labels: maintenance

#751 add hook to observe pending sessions
  jupyter_server/services/sessions/sessionmanager.py
  tests/services/sessions/test_manager.py
Labels: feature

#767 Automated Changelog Entry for 1.16.0 on main
  CHANGELOG.md
Labels: documentation

#769 Use test-sdist from maintainer-tools
  .github/workflows/python-tests.yml
Labels: maintenance
