Repository jupyter-server/jupyter_server, pull requests merged in 2022-07, with the labels that each got.

#904 Automated Changelog Entry for 1.18.1 on 1.x
  CHANGELOG.md
Labels: documentation

#907 Automated Changelog Entry for 2.0.1 on main
  CHANGELOG.md
Labels: documentation

#906 default to system node version in precommit
  .pre-commit-config.yaml
Labels: maintenance

#908 Fix owasp link
  docs/source/operators/public-server.rst
Labels: maintenance

#909 Backport PR #908 on branch 1.x (Fix owasp link)
  docs/source/operators/public-server.rst
Labels: maintenance

#910 Add back support for kernel launch timeout pad
  jupyter_server/gateway/gateway_client.py
  tests/test_gateway.py
Labels: bug, backport-1.x

#825 consolidate auth config on IdentityProvider
  .pre-commit-config.yaml
  examples/identity/system_password/README.md
  examples/identity/system_password/jupyter_server_config.py
  jupyter_server/auth/identity.py
  jupyter_server/auth/login.py
  jupyter_server/auth/logout.py
  jupyter_server/auth/security.py
  jupyter_server/base/handlers.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  pyproject.toml
  tests/auth/test_identity.py
  tests/auth/test_legacy_login.py
  tests/auth/test_login.py
  tests/extension/test_launch.py
  tests/services/api/test_api.py
  tests/test_serverapp.py
Labels: enhancement

#879 Make it easier for extensions to customize the ServerApp
  jupyter_server/extension/application.py
Labels: enhancement

#914 Backport PR #913 on branch 1.x (Fix handling of dev version)
  .github/workflows/check-release.yml
  RELEASE.md
Labels: maintenance

#917 Fix c.GatewayClient.url snippet syntax
  docs/source/operators/public-server.rst
Labels: bug

#918 Backport PR #917 on branch 1.x (Fix c.GatewayClient.url snippet syntax)
  docs/source/operators/public-server.rst
Labels: bug

#920 Backport Inject session identifier into environment variable. #679
  jupyter_server/services/sessions/sessionmanager.py
Labels: feature, backport-1.x

#922 Improve logging of bare exceptions and other cleanups.
  jupyter_server/base/handlers.py
  jupyter_server/extension/manager.py
  jupyter_server/services/kernels/kernelmanager.py
  tests/extension/test_app.py
Labels: maintenance

#925 Automated Changelog Entry for 2.0.0b0 on main
  CHANGELOG.md
Labels: documentation

#926 Backport PR #922: Improve logging of bare exceptions etc.
  jupyter_server/base/handlers.py
  jupyter_server/extension/manager.py
  jupyter_server/services/kernels/kernelmanager.py
  tests/extension/test_app.py
Labels: maintenance

#895 Allow new file types
  jupyter_server/services/contents/handlers.py
Labels: enhancement

#863 Adds anonymous users
  jupyter_server/auth/identity.py
  jupyter_server/auth/utils.py
Labels: enhancement

#915 Fix typo in IdentityProvider documentation
  docs/source/operators/security.rst
Labels: documentation

#935 avoid creating asyncio.Lock at import time
  jupyter_server/services/nbconvert/handlers.py
Labels: bug

#936 Backport PR #935 on branch 1.x (avoid creating asyncio.Lock at import time)
  jupyter_server/services/nbconvert/handlers.py
Labels: bug

#937 Fix error that prevents posting to `api/contents` endpoint with no body
  jupyter_server/services/contents/handlers.py
  tests/services/contents/test_api.py
Labels: bug
