Repository jupyter-server/jupyter_server, pull requests merged in 2022-01, with the labels that each got.

#652 Print IPv6 url as hostname or enclosed in brackets
  jupyter_server/serverapp.py
Labels: enhancement

#655 Don't block the event loop when exporting with nbconvert
  jupyter_server/nbconvert/handlers.py
Labels: enhancement

#654 Add more awaits for pending kernel in unit tests
  jupyter_server/tests/services/kernels/test_api.py
Labels: enhancement

#656 Automated Changelog Entry for 1.13.2 on main
  CHANGELOG.md
Labels: enhancement

#662 More updates to unit tests for pending kernels work
  jupyter_server/tests/services/sessions/test_api.py
Labels: enhancement

#663 bump traitlets dependency
  setup.cfg
Labels: bug

#665 Automated Changelog Entry for 1.13.3 on main
  CHANGELOG.md
Labels: documentation

#664 Remove codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#667 Fix nbconvert handler run_sync()
  jupyter_server/nbconvert/handlers.py
Labels: bug

#673 (temporarily) skip pending kernels unit tests on Windows CI
  jupyter_server/tests/services/kernels/test_api.py
  jupyter_server/tests/services/kernels/test_cull.py
  jupyter_server/tests/services/sessions/test_api.py
Labels: maintenance

#669 make unit tests backwards compatible without pending kernels
  .github/workflows/python-linux.yml
  jupyter_server/pytest_plugin.py
  jupyter_server/tests/services/kernels/test_api.py
  jupyter_server/tests/services/kernels/test_cull.py
  jupyter_server/tests/services/sessions/test_api.py
  setup.cfg
Labels: bug

#670 Fix the non-writable path deletion error
  jupyter_server/services/contents/filemanager.py
Labels: bug

#681 Pin pywintpy for now
  setup.cfg
Labels: bug

#683 Fix a typo
  jupyter_server/services/sessions/sessionmanager.py
Labels: maintenance
