Repository jupyter-server/jupyter_server, pull requests merged in 2022-06, with the labels that each got.

#865 Fix sphinx 5.0 support
  docs/source/conf.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
Labels: maintenance

#867 Fix lint
  tests/services/contents/test_api.py
Labels: maintenance

#872 Backport PR #865 on branch 1.x (Fix sphinx 5.0 support)
  docs/source/conf.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
Labels: maintenance

#870 Add changelog for 2.0.0a1
  CHANGELOG.md
Labels: documentation

#874 Fix gateway kernel shutdown
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#875 Backport PR #874 on branch 1.x (Fix gateway kernel shutdown)
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#878 Show import error when faiing to load an extension
  jupyter_server/extension/manager.py
Labels: enhancement

#880 Backport PR #878 on branch 1.x (Show import error when faiing to load an extension)
  jupyter_server/extension/manager.py
Labels: enhancement

#882 suppress tornado deprecation warnings
  pyproject.toml
Labels: maintenance

#886 Normalize os_path
  jupyter_server/utils.py
Labels: maintenance

#888 Backport PR #886 on branch 1.x (Normalize os_path)
  jupyter_server/utils.py
Labels: maintenance

#890 Automated Changelog Entry for 1.18.0 on 1.x
  CHANGELOG.md
Labels: documentation

#892 Make ChannelQueue.get_msg true async
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#896 Notify ChannelQueue that the response router thread is finishing
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#897 Backport PR #896 on branch 1.x (Notify ChannelQueue that the response router thread is finishing)
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug
