Repository jupyter-server/jupyter_server, pull requests merged in 2022-11, with the labels that each got.

#1035 Better Handling of Asyncio
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
  examples/simple/README.md
  examples/simple/pytest.ini
  examples/simple/setup.py
  jupyter_server/__init__.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/auth/test_legacy_login.py
  tests/extension/test_app.py
  tests/services/contents/test_config.py
  tests/services/kernels/test_api.py
  tests/services/kernels/test_config.py
  tests/test_gateway.py
  tests/test_paths.py
  tests/test_serverapp.py
  tests/test_terminal.py
Labels: enhancement

#1046 Pass kernel environment to `cwd_for_path` method
  jupyter_server/services/kernels/kernelmanager.py
Labels: enhancement

#1044 Clean up handling of synchronous managers
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
  pyproject.toml
  tests/services/contents/test_api.py
  tests/services/contents/test_config.py
  tests/services/kernels/test_api.py
  tests/services/kernels/test_cull.py
  tests/services/sessions/test_api.py
Labels: maintenance

#1049 Fix min version check again
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: bug

#1052 [1.x] Switch to releaser v2 and update workflows
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/python-tests.yml
  README.md
Labels: maintenance

#1053 Add dependabot file
  .github/dependabot.yml
Labels: maintenance

#1061 MAINT: remove python 3.4 branch
  jupyter_server/base/zmqhandlers.py
Labels: maintenance

#1064 Test notebook prerelease
  .github/workflows/downstream.yml
  tests/extension/test_serverextension.py
Labels: maintenance

#1065 Test downstream jupyter_server_terminals
  .github/workflows/downstream.yml
Labels: maintenance

#1066 Increase nbconvert and checkpoints coverage
  .github/workflows/python-tests.yml
  jupyter_server/services/contents/checkpoints.py
  tests/conftest.py
  tests/services/contents/test_api.py
  tests/services/contents/test_checkpoints.py
Labels: bug, maintenance

#1068 Fix config merge test for Jupyter Core 5.0
  tests/extension/test_serverextension.py
Labels: maintenance

#1067 More coverage
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
  codecov.yml
  jupyter_server/serverapp.py
  pyproject.toml
  tests/test_utils.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: maintenance

#1071 use recommended github-workflows checker
  .pre-commit-config.yaml
Labels: maintenance

#844 docs: document the logging_config trait
  docs/source/conf.py
  docs/source/operators/configuring-logging.rst
  docs/source/operators/index.rst
  pyproject.toml
Labels: documentation

#1069 Add more coverage
  .github/workflows/python-tests.yml
  jupyter_server/files/handlers.py
  pyproject.toml
  tests/extension/test_serverextension.py
  tests/extension/test_utils.py
  tests/test_files.py
  tests/test_utils.py
Labels: bug, maintenance

#1074 Fix hatch scripts and windows workflow run
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: maintenance

#1073 Fix rename_file and delete_file to handle hidden files properly
  jupyter_server/services/contents/filemanager.py
  tests/services/contents/test_manager.py
Labels: bug

#1075 Backport PR #1073 on branch 1.x (Fix rename_file and delete_file to handle hidden files properly)
  jupyter_server/services/contents/filemanager.py
  tests/services/contents/test_manager.py
Labels: bug

#1021 Add authorization to AuthenticatedFileHandler
  jupyter_server/auth/authorizer.py
  jupyter_server/base/handlers.py
Labels: enhancement

#1077 More cleanup
  .github/workflows/check-release.yml
  .github/workflows/downstream.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
  README.md
Labels: maintenance

#1047 New configurable/overridable kernel ZMQ+Websocket connection API
  jupyter_server/base/websocket.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/connection/__init__.py
  jupyter_server/services/kernels/connection/abc.py
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/websocket.py
  pyproject.toml
  tests/services/sessions/test_api.py
  tests/test_serialize.py
Labels: enhancement

#1078 Add more gateway tests
  jupyter_server/gateway/handlers.py
  tests/test_gateway.py
Labels: maintenance

#1079 Add more serverapp tests
  .github/workflows/integration-tests.yml
  pyproject.toml
  tests/test_serverapp.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: maintenance

#1083 Tornado WebSocketHandler fixup
  jupyter_server/base/zmqhandlers.py
  jupyter_server/services/kernels/connection/channels.py
Labels: bug

#1089 Use handle_outgoing_message for ZMQ replies
  jupyter_server/services/kernels/connection/channels.py
Labels: bug

#1085 Add more websocket connection tests and fix bugs
  jupyter_server/services/kernels/connection/channels.py
  tests/services/kernels/test_connection.py
Labels: bug, maintenance

#1090 Add base handler tests
  jupyter_server/base/handlers.py
  tests/test_handlers.py
Labels: maintenance

#1091 Fix coverage upload
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
Labels: maintenance

#1092 Add more tests
  jupyter_server/pytest_plugin.py
  tests/base/test_handlers.py
  tests/base/test_websocket.py
  tests/services/contents/test_fileio.py
  tests/test_serverapp.py
Labels: maintenance

#1095 Defer webbrowser import
  jupyter_server/serverapp.py
Labels: bug

#1097 Backport PR #1095 on branch 1.x (Defer webbrowser import)
  jupyter_server/serverapp.py
Labels: bug

#1098 Clean up release instructions and coverage handling
  RELEASE.md
  pyproject.toml
Labels: maintenance

#1099 Use pytest-jupyter
  .github/workflows/downstream.yml
  .github/workflows/python-tests.yml
  jupyter_server/pytest_plugin.py
  pyproject.toml
  tests/services/kernelspecs/test_api.py
  tests/services/sessions/test_api.py
Labels: maintenance

#1101 Introduce ServerKernelManager class
  jupyter_server/services/kernels/kernelmanager.py
  tests/services/kernels/test_config.py
Labels: enhancement

#1093 Import ensure_async from jupyter_core
  jupyter_server/utils.py
  pyproject.toml
Labels: maintenance
