Repository jupyter-server/jupyter_server, pull requests merged in 2022-05, with the labels that each got.

#824 CI cleanup
  .github/workflows/python-tests.yml
Labels: maintenance

#823 Switch to flit
  .flake8
  MANIFEST.in
  RELEASE.md
  package-lock.json
  package.json
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#826 Defer preferred_dir validation until root_dir is set
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: bug

#827 Add license metadata and file
  pyproject.toml
Labels: maintenance

#828 Backport PR #826 on branch 1.x (Defer preferred_dir validation until root_dir is set)
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: bug

#779 Add mypy check
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/authorization/jupyter_nbclassic_readonly_config.py
  examples/authorization/jupyter_nbclassic_rw_config.py
  examples/authorization/jupyter_temporary_config.py
  examples/simple/jupyter_server_config.py
  examples/simple/jupyter_simple_ext11_config.py
  examples/simple/jupyter_simple_ext1_config.py
  examples/simple/jupyter_simple_ext2_config.py
  jupyter_server/auth/login.py
  jupyter_server/auth/security.py
  jupyter_server/auth/utils.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/manager.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/i18n/__init__.py
  jupyter_server/py.typed
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/config/manager.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/auth/test_identity.py
  tests/auth/test_login.py
  tests/extension/test_app.py
  tests/nbconvert/test_handlers.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
  tests/services/kernels/test_api.py
  tests/services/kernelspecs/test_api.py
  tests/services/sessions/test_api.py
  tests/services/sessions/test_manager.py
  tests/test_files.py
  tests/test_gateway.py
  tests/test_paths.py
  tests/test_serverapp.py
  tests/unix_sockets/test_serverapp_integration.py
  tests/utils.py
Labels: maintenance

#831 Backport PR #779 on branch 1.x (Add mypy check)
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/authorization/jupyter_nbclassic_readonly_config.py
  examples/authorization/jupyter_nbclassic_rw_config.py
  examples/authorization/jupyter_temporary_config.py
  examples/simple/jupyter_server_config.py
  examples/simple/jupyter_simple_ext11_config.py
  examples/simple/jupyter_simple_ext1_config.py
  examples/simple/jupyter_simple_ext2_config.py
  jupyter_server/auth/login.py
  jupyter_server/auth/security.py
  jupyter_server/auth/utils.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/manager.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/i18n/__init__.py
  jupyter_server/py.typed
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/config/manager.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/__init__.py
  jupyter_server/terminal/api_handlers.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/auth/test_login.py
  tests/extension/test_app.py
  tests/nbconvert/test_handlers.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
  tests/services/kernels/test_api.py
  tests/services/kernelspecs/test_api.py
  tests/services/sessions/test_api.py
  tests/services/sessions/test_manager.py
  tests/test_files.py
  tests/test_gateway.py
  tests/test_paths.py
  tests/test_serverapp.py
  tests/unix_sockets/test_serverapp_integration.py
  tests/utils.py
Labels: maintenance

#832 Automated Changelog Entry for 2.0.0a0 on main
  CHANGELOG.md
Labels: documentation

#817 move isort, black config to pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#811 Automated Changelog Entry Forward Ported from v1.17.0
  CHANGELOG.md
Labels: documentation

#830 give authorizer handle on identity provider
  jupyter_server/auth/authorizer.py
  jupyter_server/base/handlers.py
  jupyter_server/serverapp.py
Labels: enhancement

#833 ensure user is defined in early short-circuit requests
  jupyter_server/base/handlers.py
Labels: bug

#835 Do not use pre-releases for build dependencies
  .github/workflows/python-tests.yml
Labels: maintenance

#836 Call "/api/shutdown" instead of "/"
  jupyter_server/serverapp.py
Labels: bug

#834 Enable GatewayClient managers to be configurable
  jupyter_server/serverapp.py
Labels: enhancement

#838 Backport PR #834 on branch 1.x (Enable GatewayClient managers to be configurable)
  jupyter_server/serverapp.py
Labels: enhancement

#837 Backport PR #836 on branch 1.x (Call "/api/shutdown" instead of "/")
  jupyter_server/serverapp.py
Labels: bug

#840 Use static versions everywhere
  docs/source/conf.py
  pyproject.toml
Labels: maintenance

#841 Fix docs version
  docs/source/conf.py
  pyproject.toml
Labels: maintenance

#848 Fix GatewayKernelClient is consuming data from other kernel instances
  jupyter_server/gateway/managers.py
Labels: bug

#820 Basic Event Bus
  jupyter_server/base/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/events/__init__.py
  jupyter_server/services/events/bus.py
  jupyter_server/services/events/handlers.py
  pyproject.toml
  tests/services/events/__init__.py
  tests/services/events/mock_event.yaml
  tests/services/events/mockextension/__init__.py
  tests/services/events/mockextension/mock_extension.py
  tests/services/events/mockextension/mock_extension_event.yaml
  tests/services/events/test_api.py
  tests/services/events/test_extension.py
Labels: enhancement

#853 [Bug] Change test domain from `*.jupyter.com/*` to `*.jupyter.org/*`
  tests/services/events/mock_event.yaml
  tests/services/events/mockextension/mock_extension.py
  tests/services/events/mockextension/mock_extension_event.yaml
  tests/services/events/test_api.py
  tests/services/events/test_extension.py
Labels: maintenance

#679 Inject session identifier into environment variable.
  jupyter_server/services/sessions/sessionmanager.py
Labels: enhancement

#860 Fix a typo on configuration.rst
  docs/source/users/configuration.rst
Labels: documentation

#859 Make start_kernel env extend os.environ
  jupyter_server/services/sessions/sessionmanager.py
Labels: bug

#845 Switch to hatch build plugin
  .github/workflows/check-release.yml
  .github/workflows/python-tests.yml
  CONTRIBUTING.rst
  package-lock.json
  pyproject.toml
Labels: maintenance

#851 Rest API endpoints for Events
  jupyter_server/services/events/handlers.py
  tests/services/events/test_api.py
Labels: feature
