Repository jupyter-server/jupyter_server, pull requests merged in 2022-09, with the labels that each got.

#958 Automated Changelog Entry for 2.0.0b1 on main
  CHANGELOG.md
Labels: documentation

#959 Don't validate certs for when stopping server
  jupyter_server/utils.py
Labels: bug

#965 Correct content-type headers
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
Labels: bug

#966 Backport PR #965: Correct content-type headers
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
Labels: bug

#972 fix issues with jupyter_events 0.5.0
  tests/services/events/mock_event.yaml
  tests/services/events/mockextension/mock_extension.py
  tests/services/events/mockextension/mock_extension_event.yaml
  tests/services/events/test_api.py
  tests/services/events/test_extension.py
Labels: bug

#949 Parse list value for `terminado_settings`
  jupyter_server/serverapp.py
  tests/test_terminal.py
Labels: bug

#969 Accept and manage cookies when requesting gateways
  jupyter_server/gateway/gateway_client.py
  tests/test_gateway.py
Labels: enhancement

#973 Run downstream tests in parallel
  .github/workflows/downstream.yml
Labels: maintenance

#977 Automated Changelog Entry for 2.0.0rc0 on main
  CHANGELOG.md
Labels: documentation

#979 [Gateway] Fix and deprecate env whitelist handling
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug, deprecation

#839 Test python 3.11 on ubuntu
  .github/workflows/python-tests.yml
Labels: maintenance

#984 Switch to using hatchling version command
  RELEASE.md
  docs/source/conf.py
  jupyter_server/_version.py
  pyproject.toml
Labels: maintenance

#985 [Gateway] Add support for gateway token renewal
  jupyter_server/gateway/gateway_client.py
  tests/test_gateway.py
Labels: enhancement

#981 Make it easier to pass custom env variables to kernel
  jupyter_server/services/sessions/sessionmanager.py
Labels: enhancement

#988 Test with client 8 updates
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
  jupyter_server/services/kernels/handlers.py
Labels: maintenance

#991 Remove hardcoded client install
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
Labels: maintenance

#994 Backport #981: Make it easier to pass custom env variables to kernel
  jupyter_server/services/sessions/sessionmanager.py
Labels: enhancement

#992 Test with client 8 updates
  docs/doc-requirements.txt
  jupyter_server/services/kernels/handlers.py
  readthedocs.yml
Labels: maintenance

#996 Automated Changelog Entry for 1.19.0 on 1.x
  CHANGELOG.md
Labels: documentation

#993 Add workflows for simplified publish
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#998 Update server extension disable instructions
  docs/source/developers/extensions.rst
Labels: documentation

#1002 Automated Changelog Entry for 1.19.1 on 1.x
  CHANGELOG.md
Labels: documentation

#1001 Wrap the concurrent futures in an asyncio future
  .github/workflows/python-tests.yml
  jupyter_server/services/kernels/handlers.py
Labels: bug

#1003 Fix some typos in release instructions
  RELEASE.md
Labels: bug

#1004 Pin docutils to fix docs build
  docs/doc-requirements.txt
Labels: documentation

#1005 Backport PR #1004 on branch 1.x (Pin docutils to fix docs build)
  docs/doc-requirements.txt
Labels: documentation

#1006 Update to version2 releaser
  .github/workflows/check-release.yml
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: maintenance
