Repository jupyter-server/jupyter_server, pull requests merged in 2022-02, with the labels that each got.

#685 Add Auto Pre-Commit
  .github/workflows/trigger_precommit.yml
Labels: maintenance

#687 Update trigger_precommit.yml
  .github/workflows/trigger_precommit.yml
Labels: maintenance

#689 Clean up full install test
  .github/workflows/python-linux.yml
  pyproject.toml
Labels: maintenance

#657 Protocol alignment
  jupyter_server/base/zmqhandlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/handlers.py
Labels: enhancement

#694 Use pytest-github-actions-annotate-failures
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
Labels: maintenance

#165 Add authorization layer to server request handlers
  docs/source/operators/security.rst
  examples/authorization/README.md
  examples/authorization/jupyter_nbclassic_readonly_config.py
  examples/authorization/jupyter_nbclassic_rw_config.py
  examples/authorization/jupyter_temporary_config.py
  jupyter_server/auth/__init__.py
  jupyter_server/auth/authorizer.py
  jupyter_server/auth/decorator.py
  jupyter_server/auth/login.py
  jupyter_server/auth/utils.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  jupyter_server/kernelspecs/handlers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/config/handlers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/kernelspecs/handlers.py
  jupyter_server/services/nbconvert/handlers.py
  jupyter_server/services/security/handlers.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/services/shutdown.py
  jupyter_server/terminal/api_handlers.py
  jupyter_server/terminal/handlers.py
  jupyter_server/terminal/terminalmanager.py
  jupyter_server/tests/auth/test_authorizer.py
  jupyter_server/tests/auth/test_utils.py
  jupyter_server/tests/extension/mockextensions/__init__.py
  jupyter_server/tests/extension/test_app.py
  jupyter_server/tests/extension/test_serverextension.py
  jupyter_server/tests/nbconvert/test_handlers.py
  jupyter_server/tests/services/contents/test_api.py
  jupyter_server/tests/services/contents/test_largefilemanager.py
  jupyter_server/tests/services/contents/test_manager.py
  jupyter_server/tests/services/kernels/test_api.py
  jupyter_server/tests/services/sessions/test_api.py
  jupyter_server/tests/test_files.py
  jupyter_server/tests/test_gateway.py
  jupyter_server/tests/test_paths.py
  jupyter_server/tests/test_traittypes.py
  jupyter_server/tests/test_utils.py
  jupyter_server/view/handlers.py
Labels: feature

#698 Refresh precommit
  .github/workflows/downstream.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-linux.yml
  .github/workflows/python-macos.yml
  .github/workflows/python-windows.yml
  .pre-commit-config.yaml
  examples/simple/simple_ext1/handlers.py
  examples/simple/simple_ext1/static/bundle.js
  jupyter_server/_sysinfo.py
  jupyter_server/auth/login.py
  jupyter_server/base/handlers.py
  jupyter_server/extension/application.py
  jupyter_server/extension/serverextension.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/kernelspecs/handlers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/checkpoints.py
  jupyter_server/services/contents/filecheckpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/largefilemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernelspecs/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/terminalmanager.py
  jupyter_server/tests/auth/test_security.py
  jupyter_server/tests/nbconvert/test_handlers.py
  jupyter_server/tests/services/contents/test_api.py
  jupyter_server/tests/services/contents/test_fileio.py
  jupyter_server/tests/services/contents/test_largefilemanager.py
  jupyter_server/tests/services/contents/test_manager.py
  jupyter_server/tests/services/sessions/test_manager.py
  jupyter_server/tests/test_files.py
  jupyter_server/tests/test_gateway.py
  jupyter_server/tests/utils.py
  jupyter_server/view/handlers.py
Labels: maintenance
