Repository jupyter-server/jupyter_server, pull requests merged in 2022-12, with the labels that each got.

#1108 Add skip-if-exists config
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: maintenance

#1110 Fix kernel WebSocket protocol
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/websocket.py
  tests/services/kernels/test_connection.py
Labels: bug

#1117 Remove left over from notebook
  docs/source/operators/security.rst
Labels: documentation

#1113 Tweak codecov settings
  codecov.yml
Labels: maintenance

#1118 Make tests less sensitive to default kernel name
  tests/services/kernelspecs/test_api.py
Labels: maintenance

#1114 Adopt ruff and use less pre-commit
  .github/dependabot.yml
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/source/conf.py
  examples/simple/setup.py
  examples/simple/simple_ext1/application.py
  examples/simple/simple_ext1/handlers.py
  examples/simple/simple_ext11/application.py
  examples/simple/simple_ext2/application.py
  examples/simple/simple_ext2/handlers.py
  jupyter_server/_sysinfo.py
  jupyter_server/_tz.py
  jupyter_server/auth/__main__.py
  jupyter_server/auth/identity.py
  jupyter_server/auth/security.py
  jupyter_server/base/handlers.py
  jupyter_server/extension/application.py
  jupyter_server/extension/manager.py
  jupyter_server/extension/serverextension.py
  jupyter_server/extension/utils.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/kernelspecs/handlers.py
  jupyter_server/log.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/contents/filecheckpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/kernels/websocket.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/api_handlers.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_identity.py
  tests/auth/test_legacy_login.py
  tests/base/test_handlers.py
  tests/extension/mockextensions/app.py
  tests/extension/test_manager.py
  tests/extension/test_serverextension.py
  tests/services/api/test_api.py
  tests/services/contents/test_fileio.py
  tests/services/events/mockextension/__init__.py
  tests/services/kernels/test_connection.py
  tests/services/sessions/test_api.py
  tests/test_gateway.py
  tests/test_serverapp.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: maintenance

#1112 [Gateway] Remove redundant list kernels request during session poll
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: enhancement

#1128 Fix lint rule
  .pre-commit-config.yaml
  jupyter_server/extension/application.py
  pyproject.toml
  tests/services/events/mockextension/__init__.py
Labels: maintenance

#1132 Logging message used to list sessions fails with template error
  jupyter_server/serverapp.py
Labels: bug

#1133 only write browser files if we're launching the browser
  jupyter_server/serverapp.py
Labels: bug

#1136 Find an available port before starting event loop
  .github/workflows/python-tests.yml
  jupyter_server/serverapp.py
Labels: bug

#1139 Raise errors on individual problematic extensions when listing extension
  jupyter_server/extension/serverextension.py
Labels: bug

#1141 Backport PR #1139 on branch 1.x (Raise errors on individual problematic extensions when listing extension)
  jupyter_server/extension/serverextension.py
Labels: bug

#1140 Revert "Make preferred_dir content manager trait"
  jupyter_server/serverapp.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  tests/test_gateway.py
  tests/test_serverapp.py
  tests/test_terminal.py
Labels: maintenance

#1138 Backport PR #1124 on branch 1.x (Include base_url at start of kernelspec resources path)
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#1144 Restore default writing of browser open redirect file, add opt-in to skip
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: bug

#1145 Fix handling of extension last activity
  jupyter_server/serverapp.py
  tests/test_terminal.py
Labels: bug

#1149 Import ensure-sync directly from dependence.
  jupyter_server/files/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/kernelspecs/handlers.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/view/handlers.py
  tests/services/contents/test_checkpoints.py
  tests/services/contents/test_largefilemanager.py
  tests/services/contents/test_manager.py
  tests/test_gateway.py
Labels: maintenance

#1148 Update deprecation warning
  jupyter_server/utils.py
Labels: maintenance

#1151 Remove `end` kwarg after migration from print to info
  jupyter_server/serverapp.py
Labels: bug

#1155 Handle flake8-errmsg
  jupyter_server/auth/identity.py
  jupyter_server/auth/security.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/manager.py
  jupyter_server/extension/serverextension.py
  jupyter_server/extension/utils.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/checkpoints.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
Labels: maintenance

#1157 Iterate through set of apps in `extension_manager.any_activity` method
  jupyter_server/extension/manager.py
Labels: bug

#1158 Fix broken link in warning message
  jupyter_server/base/handlers.py
Labels: maintenance
