Repository jupyter-server/jupyter_server, pull requests merged in 2022-08, with the labels that each got.

#939 Fix bug in `api/contents` requests for an allowed copy
  jupyter_server/services/contents/handlers.py
Labels: bug

#941 Fix flake8 v5 compat
  .pre-commit-config.yaml
Labels: maintenance

#944 Retry certain errors between server and gateway
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
Labels: enhancement

#946 Backport PR #944 on branch 1.x (Retry certain errors between server and gateway)
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
Labels: enhancement

#952 Fix docs build
  docs/doc-requirements.txt
  docs/environment.yml
  readthedocs.yml
Labels: maintenance

#887 Check for serverapp for reraise flag
  jupyter_server/extension/manager.py
  tests/extension/test_manager.py
Labels: bug

#954 Emit events from the Contents Service
  jupyter_server/__init__.py
  jupyter_server/event_schemas/contents_service/v1.yaml
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
  jupyter_server/services/contents/manager.py
Labels: enhancement

#956 Update pytest_plugin with fixtures to test auth in core and extensions
  examples/simple/simple_ext1/handlers.py
  examples/simple/tests/test_handlers.py
  jupyter_server/pytest_plugin.py
  tests/auth/test_authorizer.py
Labels: maintenance
