Repository jupyter-server/jupyter_server, pull requests merged in 2022-04, with the labels that each got.

#771 Add explicit handling of warnings
  .github/workflows/python-tests.yml
  docs/source/operators/multiple-extensions.rst
  jupyter_server/pytest_plugin.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/extension/test_launch.py
  tests/extension/test_serverextension.py
  tests/services/kernelspecs/test_api.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: maintenance

#675 update some metadata fields, sort deps
  setup.cfg
Labels: maintenance

#772 Update team meetings doc
  docs/source/contributors/team-meetings.rst
Labels: documentation

#776 Give write permissions to enforce label workflow
  .github/workflows/enforce-label.yml
Labels: maintenance

#777 Use new post-version-spec from jupyter_releaser
  pyproject.toml
Labels: maintenance

#770 Update documentation about registering file save hooks
  docs/source/developers/savehooks.rst
Labels: documentation

#782 Clean up pre-commit
  .github/workflows/python-tests.yml
  .github/workflows/trigger_precommit.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
Labels: maintenance

#788 Hydrate a Kernel Manager when calling GatewayKernelManager.start_kernel with a kernel_id
  jupyter_server/gateway/managers.py
Labels: enhancement

#651 Remove terminals in favor of jupyter_server_terminals extension
  .pre-commit-config.yaml
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/manager.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/terminal/__init__.py
  jupyter_server/terminal/api_handlers.py
  jupyter_server/terminal/handlers.py
  jupyter_server/terminal/terminalmanager.py
  setup.cfg
  tests/extension/test_app.py
  tests/test_terminal.py
Labels: enhancement

#794 Fix contributing guide for building the docs
  .gitignore
  CONTRIBUTING.rst
  docs/doc-requirements.txt
  docs/source/other/full-config.rst
Labels: documentation

#791 Update branch references and links
  .github/workflows/check-release.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
  README.md
  docs/README.md
  docs/source/developers/extensions.rst
  docs/source/index.rst
Labels: maintenance

#795 Backport PR #793 on branch 1.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: maintenance

#799 Backport PR #798 on branch 1.x (missing required arguments in utils.fetch)
  jupyter_server/serverapp.py
  jupyter_server/utils.py
Labels: bug

#800 Fix path for full config doc
  docs/autogen_config.py
Labels: documentation

#805 Backport PR #804 on branch 1.x (Add the root_dir value to the logging message in case of non compliant preferred_dir)
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: enhancement

#801 Add Jupyter Server Architecture diagram
  docs/source/developers/architecture.rst
  docs/source/developers/extensions.rst
  docs/source/developers/index.rst
  docs/source/images/jupyter-server-architecture.drawio.png
Labels: documentation

#797 Add helper jobs for branch protection
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
Labels: maintenance

#807 Backport PR #797 on branch 1.x (Add helper jobs for branch protection)
  .github/workflows/integration-tests.yml
  .github/workflows/python-tests.yml
Labels: maintenance

#810 Automated Changelog Entry for 1.17.0 on 1.x
  CHANGELOG.md
Labels: documentation

#808 Add Session workflows documentation
  docs/source/developers/architecture.rst
  docs/source/images/session-create.drawio.png
  docs/source/images/session-delete.drawio.png
Labels: documentation

#813 Remove duplicate requests requirement from setup.cfg
  setup.cfg
Labels: maintenance, dependencies

#815 (backport) ensure authorizer is defined
  jupyter_server/auth/decorator.py
  jupyter_server/auth/utils.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/terminal/handlers.py
Labels: enhancement

#671 Identity API at /api/me
  docs/source/conf.py
  docs/source/operators/security.rst
  jupyter_server/auth/__init__.py
  jupyter_server/auth/authorizer.py
  jupyter_server/auth/decorator.py
  jupyter_server/auth/identity.py
  jupyter_server/auth/login.py
  jupyter_server/auth/utils.py
  jupyter_server/base/handlers.py
  jupyter_server/base/zmqhandlers.py
  jupyter_server/gateway/handlers.py
  jupyter_server/log.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/api.yaml
  jupyter_server/services/api/handlers.py
  tests/auth/test_identity.py
  tests/auth/test_login.py
  tests/services/api/test_api.py
Labels: feature

#819 Backport PR #792 on branch 1.x (Centralize app cleanup)
  .github/workflows/python-tests.yml
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/kernelmanager.py
  tests/auth/test_authorizer.py
  tests/services/kernels/test_api.py
  tests/services/kernels/test_cull.py
  tests/services/sessions/test_api.py
  tests/test_terminal.py
Labels: maintenance
