Repository jupyter-server/jupyter_server, pull requests merged in 2023-11, with the labels that each got.

#1350 Update typing for traitlets 5.13
  jupyter_server/extension/application.py
  jupyter_server/extension/manager.py
  jupyter_server/extension/serverextension.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/kernelmanager.py
  pyproject.toml
  tests/extension/mockextensions/app.py
  tests/services/kernels/test_connection.py
Labels: maintenance

#1351 Clean up lint and typing
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  examples/identity/system_password/jupyter_server_config.py
  jupyter_server/__init__.py
  jupyter_server/auth/__init__.py
  jupyter_server/auth/__main__.py
  jupyter_server/auth/security.py
  jupyter_server/base/handlers.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/connections.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/kernelspecs/handlers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/prometheus/log_functions.py
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/config/__init__.py
  jupyter_server/services/config/handlers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernelspecs/handlers.py
  jupyter_server/services/nbconvert/handlers.py
  jupyter_server/services/security/handlers.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/services/shutdown.py
  jupyter_server/utils.py
  jupyter_server/view/handlers.py
  pyproject.toml
Labels: maintenance

#1353 Clean up config and address warnings
  jupyter_server/_tz.py
  pyproject.toml
  tests/test_gateway.py
Labels: maintenance

#1354 Update kernel env to reflect changes in session
  jupyter_server/services/sessions/sessionmanager.py
Labels: enhancement

#1357 ContentsHandler return 404 rather than raise exc
  jupyter_server/services/contents/handlers.py
  tests/services/contents/test_manager.py
Labels: bug

#1356 Add more typings
  jupyter_server/_tz.py
  jupyter_server/auth/decorator.py
  jupyter_server/auth/identity.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/serverextension.py
  jupyter_server/gateway/connections.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/i18n/__init__.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/config/manager.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/connection/abc.py
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
Labels: maintenance

#1361 typo: ServerApp
  docs/source/developers/architecture.rst
Labels: documentation

#1363 Support get file(notebook) md5
  docs/source/developers/contents.rst
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  tests/services/contents/test_api.py
  tests/services/contents/test_fileio.py
  tests/services/contents/test_manager.py
Labels: enhancement

#1364 Update api docs with md5 param
  jupyter_server/services/api/api.yaml
Labels: documentation

#1367 Change md5 to hash and hash_algorithm, fix incompatibility
  .github/workflows/downstream.yml
  docs/source/developers/contents.rst
  jupyter_server/services/api/api.yaml
  jupyter_server/services/contents/filecheckpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  tests/services/contents/test_api.py
  tests/services/contents/test_fileio.py
  tests/services/contents/test_manager.py
  tests/services/contents/test_manager_no_hash.py
Labels: bug

#1369 avoid unhandled error on some invalid paths
  jupyter_server/services/contents/fileio.py
Labels: bug
