Repository jupyter-server/jupyter_server, pull requests merged in 2023-02, with the labels that each got.

#1189 Adopt more lint rules
  .pre-commit-config.yaml
  jupyter_server/auth/__main__.py
  jupyter_server/auth/identity.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/manager.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  jupyter_server/i18n/__init__.py
  jupyter_server/log.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_identity.py
  tests/extension/test_launch.py
  tests/extension/test_manager.py
  tests/services/contents/test_api.py
  tests/services/contents/test_fileio.py
  tests/services/contents/test_manager.py
  tests/test_gateway.py
Labels: maintenance

#1194 Delete the extra "or" in front of the second url
  jupyter_server/serverapp.py
Labels: maintenance

#1196 Add license 2 (#1196
  LICENSE
  jupyter_server/log.py
  pyproject.toml
Labels: maintenance

#1197 update LICENSE
  LICENSE
Labels: maintenance

#1193 Fix get_loader returning None when load_jupyter_server_extension is not found (#1193)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
  jupyter_server/extension/utils.py
  tests/extension/mockextensions/mockext_deprecated.py
  tests/extension/test_utils.py
Labels: bug

#1200 Update jupyterhub security link
  docs/source/operators/public-server.rst
Labels: documentation

#1199 Backport PR #1193: Fix get_loader returning None when load_jupyter_server_extension is not found (#1193) (#1199)Co-authored-by: Steven Silvester <steven.silvester@ieee.org> Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
  jupyter_server/extension/utils.py
  tests/extension/mockextensions/mockext_deprecated.py
  tests/extension/test_utils.py
Labels: bug

#1201 Backport PR #1200 on branch 1.x (Update jupyterhub security link)
  docs/source/operators/public-server.rst
Labels: documentation

#1207 Support IPV6 in _find_http_port()
  jupyter_server/serverapp.py
Labels: enhancement

#1212 Redact tokens, etc. in url parameters from request logs
  jupyter_server/log.py
Labels: bug

#1214 Backport PR #1212: Redact tokens, etc. in url parameters from request logs
  jupyter_server/log.py
Labels: bug

#1218 Clean up license
  LICENSE
  README.md
Labels: maintenance

#1219 Ensure content-type properly reflects gateway kernelspec resources
  jupyter_server/base/handlers.py
  jupyter_server/gateway/handlers.py
  tests/test_gateway.py
Labels: bug

#1222 Fix ci failures
  .github/workflows/integration-tests.yml
  tests/services/contents/test_manager.py
Labels: maintenance

#1190 Enable users to copy both files and directories
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
Labels: enhancement
