Repository jupyter-server/jupyter_server, pull requests merged in 2023-10, with the labels that each got.

#1333 Add typings to commonly used APIs
  examples/simple/simple_ext1/handlers.py
  examples/simple/simple_ext2/handlers.py
  jupyter_server/_tz.py
  jupyter_server/auth/decorator.py
  jupyter_server/auth/identity.py
  jupyter_server/auth/login.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/extension/handler.py
  jupyter_server/extension/serverextension.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/connections.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernelspecs/handlers.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/shutdown.py
  jupyter_server/utils.py
  pyproject.toml
  tests/base/test_handlers.py
  tests/services/sessions/test_manager.py
  tests/test_gateway.py
  tests/test_utils.py
Labels: maintenance

#1337 Update typings for mypy 1.6
  docs/source/conf.py
  examples/identity/system_password/jupyter_server_config.py
  examples/simple/simple_ext11/application.py
  jupyter_server/gateway/managers.py
  jupyter_server/prometheus/metrics.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/utils.py
  pyproject.toml
  tests/test_terminal.py
Labels: maintenance

#1336 Added Logs for get_os_path closes issue
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  tests/services/contents/test_fileio.py
Labels: enhancement

#1340 Run Gateway token renewers even if the auth token is empty.
  jupyter_server/gateway/gateway_client.py
  tests/test_gateway.py
Labels: bug

#1342 Ability to configure cull_idle_timeout with kernelSpec
  jupyter_server/services/kernels/kernelmanager.py
  tests/services/kernels/test_cull.py
Labels: enhancement

#1341 Update kernel env to reflect changes in session.
  jupyter_server/services/sessions/sessionmanager.py
Labels: enhancement

#1346 Revert "Update kernel env to reflect changes in session."
  jupyter_server/services/sessions/sessionmanager.py
Labels: bug

#1344 Update typings and fix tests
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyter_server/base/handlers.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/utils.py
  pyproject.toml
  tests/services/sessions/test_manager.py
Labels: maintenance
