Repository jupyter-server/jupyter_server, pull requests merged in 2023-01, with the labels that each got.

#1162 Reapply preferred_dir fix, now with better backwards compatability
  jupyter_server/serverapp.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  tests/test_gateway.py
  tests/test_serverapp.py
  tests/test_terminal.py
Labels: bug, backport-1.x

#1163 Fix check release by ignoring duplicate file name in wheel
  pyproject.toml
Labels: maintenance

#1167 Backport PR #1162: Reapply preferred_dir fix, now with better backwards compatability
  jupyter_server/serverapp.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  pyproject.toml
  setup.cfg
  tests/test_gateway.py
  tests/test_serverapp.py
Labels: bug

#1169 Update example to use hatch
  .gitignore
  examples/simple/pyproject.toml
  examples/simple/setup.py
  examples/simple/simple_ext1/static/bundle.js
  examples/simple/simple_ext1/static/index.js
  examples/simple/simple_ext1/static/tsconfig.tsbuildinfo
Labels: maintenance

#1171 Log how long each extension module takes to import
  jupyter_server/extension/utils.py
Labels: enhancement

#1100 Set JPY_SESSION_NAME to full notebook path.
  jupyter_server/base/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/utils.py
  tests/services/sessions/test_manager.py
  tests/utils.py
Labels: enhancement

#1168 Clean up docs build and typing
  docs/Makefile
  docs/autogen_config.py
  docs/source/conf.py
  examples/identity/system_password/jupyter_server_config.py
  jupyter_server/gateway/managers.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/__init__.py
  jupyter_server/terminal/api_handlers.py
  jupyter_server/terminal/terminalmanager.py
  jupyter_server/utils.py
  pyproject.toml
  tests/test_terminal.py
Labels: maintenance

#1173 Fix preferred_dir for sync contents manager
  jupyter_server/services/contents/manager.py
  tests/test_serverapp.py
Labels: bug

#1159 Add api docs
  .github/workflows/python-tests.yml
  docs/source/api/jupyter_server.auth.rst
  docs/source/api/jupyter_server.base.rst
  docs/source/api/jupyter_server.extension.rst
  docs/source/api/jupyter_server.files.rst
  docs/source/api/jupyter_server.gateway.rst
  docs/source/api/jupyter_server.i18n.rst
  docs/source/api/jupyter_server.kernelspecs.rst
  docs/source/api/jupyter_server.nbconvert.rst
  docs/source/api/jupyter_server.prometheus.rst
  docs/source/api/jupyter_server.rst
  docs/source/api/jupyter_server.services.api.rst
  docs/source/api/jupyter_server.services.config.rst
  docs/source/api/jupyter_server.services.contents.rst
  docs/source/api/jupyter_server.services.events.rst
  docs/source/api/jupyter_server.services.kernels.connection.rst
  docs/source/api/jupyter_server.services.kernels.rst
  docs/source/api/jupyter_server.services.kernelspecs.rst
  docs/source/api/jupyter_server.services.nbconvert.rst
  docs/source/api/jupyter_server.services.rst
  docs/source/api/jupyter_server.services.security.rst
  docs/source/api/jupyter_server.services.sessions.rst
  docs/source/api/jupyter_server.view.rst
  docs/source/api/modules.rst
  docs/source/conf.py
  docs/source/developers/index.rst
  docs/source/operators/security.rst
  jupyter_server/auth/authorizer.py
  jupyter_server/auth/identity.py
  jupyter_server/extension/application.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/services/contents/checkpoints.py
  jupyter_server/services/contents/fileio.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/utils.py
  pyproject.toml
Labels: documentation

#1176 Pass in a logger to get_metadata
  jupyter_server/extension/manager.py
Labels: enhancement

#1179 Update jupyter client api docs links
  docs/source/developers/architecture.rst
Labels: maintenance

#1180 Only load enabled extension packages
  jupyter_server/extension/manager.py
  tests/extension/test_manager.py
Labels: enhancement

#1182 Don't assume that resources entries are relative
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: bug

#1183 Fix docs and examples
  examples/simple/webpack.config.js
  jupyter_server/services/sessions/sessionmanager.py
Labels: maintenance

#1184 Update example npm deps
  .github/workflows/python-tests.yml
  examples/simple/package.json
Labels: maintenance

#1185 Use repr in logging for exception.
  jupyter_server/extension/manager.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
Labels: maintenance

#1188 Updates for client 8
  jupyter_server/gateway/managers.py
  jupyter_server/services/kernels/kernelmanager.py
Labels: maintenance
