Repository jupyter-server/jupyter_server, pull requests merged in 2023-04, with the labels that each got.

#1254 Use debug-level messages for generating anonymous users
  jupyter_server/auth/identity.py
Labels: enhancement

#1256 Gateway manager retry kernel updates
  jupyter_server/gateway/managers.py
  tests/test_gateway.py
Labels: enhancement

#1251 Define a CURRENT_JUPYTER_HANDLER context var
  docs/source/api/jupyter_server.base.rst
  jupyter_server/__init__.py
  jupyter_server/base/call_context.py
  jupyter_server/base/handlers.py
  tests/base/test_call_context.py
Labels: enhancement

#1252 Emit events from the kernels service and gateway client
  jupyter_server/event_schemas/gateway_client/v1.yaml
  jupyter_server/event_schemas/kernel_actions/v1.yaml
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/kernelmanager.py
  pyproject.toml
  tests/services/kernels/test_events.py
  tests/test_gateway.py
Labels: feature

#1262 Fix typo
  docs/source/operators/multiple-extensions.rst
Labels: documentation
