Repository jupyter-server/jupyter_server, pull requests merged in 2023-06, with the labels that each got.

#1289 Handle test failures
  .github/workflows/python-tests.yml
  pyproject.toml
  tests/test_terminal.py
Labels: maintenance

#1282 Try testing against python 3.12
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: maintenance

#1288 Add missing events to gateway client
  jupyter_server/gateway/gateway_client.py
Labels: bug

#1292 Remove frontend doc
  docs/source/operators/public-server.rst
Labels: documentation

#1294 Reference current_user to detect auth
  jupyter_server/base/handlers.py
Labels: bug
