Repository jupyter-server/jupyter_server, pull requests merged in 2023-03, with the labels that each got.

#1223 Fix priority of deprecated NotebookApp.notebook_dir behind ServerApp.root_dir (#1223
  jupyter_server/serverapp.py
  tests/test_serverapp.py
Labels: bug

#1225 fix docs build
  pyproject.toml
Labels: maintenance

#1226 Optimize hidden checks
  jupyter_server/base/handlers.py
  jupyter_server/files/handlers.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/handlers.py
  tests/base/test_handlers.py
  tests/services/contents/test_api.py
  tests/services/contents/test_manager.py
  tests/test_files.py
Labels: enhancement, python

#1229 Fix port selection
  jupyter_server/serverapp.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: bug

#1230 Update ruff
  .pre-commit-config.yaml
  jupyter_server/auth/identity.py
  jupyter_server/auth/login.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/extension/application.py
  jupyter_server/files/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/manager.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/traittypes.py
  jupyter_server/utils.py
  pyproject.toml
  tests/conftest.py
  tests/services/contents/test_fileio.py
Labels: maintenance

#1233 Added error propagation to gateway_request function
  jupyter_server/gateway/gateway_client.py
Labels: enhancement

#1234 Backport PR #1233 on branch 1.x (Added error propagation to gateway_request function) (#1234)Co-authored-by: Broden Wanner <broden.wanner@outlook.com> Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com> Co-authored-by: Steven Silvester <steven.silvester@ieee.org>
  CHANGELOG.md
  jupyter_server/gateway/gateway_client.py
Labels: enhancement

#1236 Enable KernelSpecResourceHandler to be async
  jupyter_server/kernelspecs/handlers.py
Labels: enhancement

#1242 Fix italics in operators security sections
  docs/source/operators/public-server.rst
  docs/source/operators/security.rst
Labels: bug, documentation

#1246 chore: move `babel` and `eslint` configuration under `package.json`
  .babelrc
  .eslintignore
  .eslintrc.json
  package.json
Labels: maintenance

#1248 chore: delete `.gitmodules`
  .gitmodules
Labels: maintenance

#1249 Register websocket handler from same module as kernel handlers
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/websocket.py
Labels: bug, backwards compat
