Repository jupyter-server/jupyter_server, pull requests merged in 2023-05, with the labels that each got.

#1269 Use Python 3.9 for the readthedocs builds
  .readthedocs.yaml
Labels: maintenance

#1270 Fix typo in docs
  docs/source/operators/security.rst
Labels: documentation

#1264 Make the kernel_websocket_protocol flag reusable.
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/kernels/connection/channels.py
Labels: bug

#1268 Allows immutable cache for static files in a directory
  jupyter_server/base/handlers.py
  jupyter_server/serverapp.py
  tests/base/test_handlers.py
  tests/test_serverapp.py
Labels: enhancement

#1261 Merge the gateway handlers into the standard handlers.
  docs/source/api/jupyter_server.gateway.rst
  jupyter_server/gateway/connections.py
  jupyter_server/gateway/handlers.py
  jupyter_server/kernelspecs/handlers.py
  jupyter_server/serverapp.py
  tests/test_gateway.py
  tests/test_serverapp.py
Labels: enhancement

#1276 Don't instantiate an unused Future in gateway connection trait
  jupyter_server/gateway/connections.py
Labels: bug

#1275 Write server list to stdout
  jupyter_server/serverapp.py
  pyproject.toml
  tests/test_serverapp.py
Labels: bug

#1278 Remove distuils and mistune pins
  pyproject.toml
Labels: maintenance

#1281 Fix DeprecationWarning from pytest-console-scripts
  tests/extension/test_entrypoint.py
Labels: maintenance
