Repository jupyter-server/jupyter_server, pull requests merged in 2023-08, with the labels that each got.

#1312 Add root `/api/` endpoint to REST spec
  jupyter_server/services/api/api.yaml
Labels: documentation

#1315 accessing API version should not count as activity
  jupyter_server/base/handlers.py
Labels: bug

#1308 Assert return value of `expected_http_error`
  jupyter_server/services/events/handlers.py
  tests/services/contents/test_manager.py
  tests/services/events/test_api.py
Labels: bug

#1305 Support external kernels
  jupyter_server/serverapp.py
  jupyter_server/services/kernels/connection/channels.py
Labels: feature
