Repository jupyter-server/jupyter_server, pull requests merged in 2023-12, with the labels that each got.

#1373 Support async Authorizers
  jupyter_server/auth/authorizer.py
  jupyter_server/auth/decorator.py
  tests/auth/test_authorizer.py
Labels: enhancement

#1375 log extension import time at debug level unless it's actually slow
  jupyter_server/extension/utils.py
Labels: enhancement

#1377 Use ruff docstring-code-format
  .pre-commit-config.yaml
  examples/simple/pyproject.toml
  jupyter_server/auth/security.py
  jupyter_server/utils.py
  pyproject.toml
Labels: maintenance

#1379 Enable htmlzip and epub on readthedocs
  .readthedocs.yaml
Labels: documentation

#1380 Update pre-commit deps
  .github/dependabot.yml
  .pre-commit-config.yaml
Labels: maintenance
