Repository jupyter-server/jupyter_server, pull requests merged in 2024-02, with the labels that each got.

#1389 fix "Shutdown" -> "Shut down"
  jupyter_server/serverapp.py
Labels: documentation

#1391 websockets: add configurations for ping interval and timeout
  jupyter_server/serverapp.py
Labels: enhancement

#1396 Add deprecation note for `ServerApp.preferred_dir`
  jupyter_server/serverapp.py
Labels: documentation

#1397 Fix color in windows log console with colorama
  jupyter_server/serverapp.py
Labels: bug

#1393 Replace _jupyter_server_extension_paths in apidocs
  jupyter_server/extension/utils.py
Labels: documentation
