Repository jupyter-server/jupyter_server, pull requests merged in 2024-05, with the labels that each got.

#1420 Removing excessive logging from reading local files
  jupyter_server/services/contents/fileio.py
Labels: enhancement

#1424 Use hatch fmt command
  .github/workflows/python-tests.yml
  docs/source/conf.py
  examples/simple/tests/test_handlers.py
  jupyter_server/_sysinfo.py
  jupyter_server/_tz.py
  jupyter_server/auth/authorizer.py
  jupyter_server/auth/security.py
  jupyter_server/auth/utils.py
  jupyter_server/base/call_context.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/gateway/connections.py
  jupyter_server/gateway/gateway_client.py
  jupyter_server/gateway/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/nbconvert/handlers.py
  jupyter_server/pytest_plugin.py
  jupyter_server/serverapp.py
  jupyter_server/services/contents/filemanager.py
  jupyter_server/services/contents/largefilemanager.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/kernels/connection/channels.py
  jupyter_server/services/kernels/handlers.py
  jupyter_server/services/kernels/kernelmanager.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/terminal/handlers.py
  jupyter_server/terminal/terminalmanager.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/auth/test_identity.py
  tests/auth/test_legacy_login.py
  tests/auth/test_login.py
  tests/base/test_websocket.py
  tests/conftest.py
  tests/extension/test_app.py
  tests/extension/test_config.py
  tests/extension/test_handler.py
  tests/extension/test_launch.py
  tests/extension/test_manager.py
  tests/nbconvert/test_handlers.py
  tests/services/api/test_api.py
  tests/services/contents/test_api.py
  tests/services/contents/test_fileio.py
  tests/services/contents/test_manager.py
  tests/services/events/test_api.py
  tests/services/events/test_extension.py
  tests/services/kernels/test_api.py
  tests/services/kernels/test_config.py
  tests/services/kernels/test_cull.py
  tests/services/sessions/test_api.py
  tests/services/sessions/test_manager.py
  tests/test_gateway.py
  tests/test_serverapp.py
  tests/test_terminal.py
  tests/unix_sockets/conftest.py
  tests/unix_sockets/test_api.py
  tests/unix_sockets/test_serverapp_integration.py
Labels: maintenance

#1426 Update simple extension examples: _jupyter_server_extension_points
  examples/simple/README.md
  examples/simple/simple_ext1/__init__.py
  examples/simple/simple_ext11/__init__.py
  examples/simple/simple_ext2/__init__.py
Labels: documentation
