Repository jupyter-server/jupyter_server, pull requests merged in 2024-12, with the labels that each got.

#1481 Handle newer jupyter_events wants string version, drop 3.8
  .github/workflows/python-tests.yml
  examples/simple/pyproject.toml
  jupyter_server/_version.py
  jupyter_server/auth/authorizer.py
  jupyter_server/base/call_context.py
  jupyter_server/base/handlers.py
  jupyter_server/config_manager.py
  jupyter_server/event_schemas/contents_service/v1.yaml
  jupyter_server/event_schemas/gateway_client/v1.yaml
  jupyter_server/event_schemas/kernel_actions/v1.yaml
  jupyter_server/files/handlers.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/config/manager.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/connection/abc.py
  jupyter_server/services/kernels/connection/base.py
  jupyter_server/services/sessions/sessionmanager.py
  jupyter_server/utils.py
  pyproject.toml
  tests/auth/test_authorizer.py
  tests/extension/mockextensions/app.py
  tests/extension/test_app.py
  tests/services/api/test_api.py
  tests/services/contents/test_manager.py
  tests/services/events/mock_event.yaml
  tests/services/events/mockextension/mock_extension_event.yaml
  tests/services/events/test_api.py
  tests/test_gateway.py
  tests/test_serverapp.py
Labels: maintenance

#1478 Better error message when starting kernel for session.
  examples/simple/simple_ext1/handlers.py
  jupyter_server/gateway/managers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/sessions/handlers.py
  pyproject.toml
Labels: enhancement

#1485 Donation link NF -> LF
  pyproject.toml
Labels: maintenance

#1477 Ignore unclosed sqlite connection in traits
  pyproject.toml
Labels: maintenance

#1435 extensions: render default templates with default static_url
  jupyter_server/extension/handler.py
  tests/extension/mockextensions/__init__.py
  tests/extension/mockextensions/app.py
  tests/extension/test_app.py
  tests/extension/test_handler.py
Labels: bug
