Repository jupyter-server/jupyter_server, pull requests merged in 2024-03, with the labels that each got.

#1392 Add an option to have authentication enabled for all endpoints by default
  jupyter_server/auth/decorator.py
  jupyter_server/auth/login.py
  jupyter_server/auth/logout.py
  jupyter_server/base/handlers.py
  jupyter_server/base/websocket.py
  jupyter_server/extension/application.py
  jupyter_server/serverapp.py
  jupyter_server/services/api/handlers.py
  jupyter_server/services/contents/handlers.py
  jupyter_server/services/events/handlers.py
  jupyter_server/services/kernels/websocket.py
  jupyter_server/utils.py
  pyproject.toml
  tests/base/test_handlers.py
  tests/base/test_websocket.py
  tests/extension/test_handler.py
  tests/test_serverapp.py
Labels: enhancement

#1399 Update release workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#1401 Pin to Pytest 7
  pyproject.toml
Labels: maintenance

#1404 Don't crash on invalid JSON in page_config (#1403)
  jupyter_server/config_manager.py
Labels: bug

#1405 Ignore zero-length page_config.json, restore previous behavior of crashing for invalid JSON
  jupyter_server/config_manager.py
Labels: bug

#1406 don't include token in dashboard link, when available
  jupyter_server/templates/page.html
Labels: enhancement
