Repository jupyter-server/jupyter_server, pull requests merged in 2024-11, with the labels that each got.

#1467 Add prometheus metric with version information
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
Labels: enhancement

#1470 Add prometheus info metrics listing server extensions + versions
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
Labels: enhancement

#1471 prometheus: Expose 3 activity metrics
  jupyter_server/prometheus/metrics.py
  jupyter_server/serverapp.py
Labels: enhancement

#1463 Return HTTP 400 when attempting to post an event with an unregistered schema
  jupyter_server/services/events/handlers.py
  tests/services/events/test_api.py
Labels: bug

#1472 Add a traitlet to disable recording HTTP request metrics
  jupyter_server/log.py
  jupyter_server/serverapp.py
Labels: enhancement

#1452 add comments to explain signal handling under jupyterhub
  jupyter_server/serverapp.py
Labels: documentation
