Repository jupyter-server/jupyter_server, pull requests merged in 2024-07, with the labels that each got.

#1433 Update documentation for `cookie_secret`
  jupyter_server/serverapp.py
Labels: documentation

#1437 Do not log environment variables passed to kernels
  jupyter_server/services/kernels/kernelmanager.py
Labels: bug

#1440 Pass session_id during Websocket connect
  jupyter_server/gateway/connections.py
  tests/test_gateway.py
Labels: bug

#1429 Improve the busy/idle execution state tracking for kernels.
  jupyter_server/services/kernels/kernelmanager.py
  tests/services/kernels/test_cull.py
  tests/services/kernels/test_execution_state.py
Labels: bug

#1442 Better hash format error message
  jupyter_server/services/contents/handlers.py
Labels: enhancement
