Repository jupyter-server/jupyter_server, pull requests merged in 2025-04, with the labels that each got.

#1505 Update Security Section in the Jupyter Server Documentation
  docs/source/operators/security.rst
Labels: documentation

#1510 tests: install test-functional requirements for Jupytext downstream tests
  .github/workflows/downstream.yml
Labels: maintenance

#1508 Update websocket-protocols documentation to reflect implementation
  docs/source/developers/websocket-protocols.rst
Labels: documentation

#1517 Update meetings notes link and zoom link
  README.md
Labels: bug
